/**
 * Seed Firms Script
 * Run with: node scripts/seed_firms.js
 * 
 * This script populates the firm_members collection with dummy data
 * including Big 4, Large, Medium, and Small firms.
 */

const { MongoClient, ObjectId } = require('mongodb');
require('dotenv').config();

// MongoDB connection URL from environment or default
const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017';
const DB_NAME = process.env.MONGO_DATABASE || 'lacpa';

// Dummy firm data
const firms = [
    // Big 4 - Deloitte
    {
        _id: new ObjectId(),
        lacpa_id: "FIRM-2024-001",
        firm_name: "Deloitte Middle East",
        logo_url: "/assets/images/firms/deloitte.svg",
        firm_type: "Audit Firm",
        firm_size: "Big 4",
        badge_color: "blue-600",
        badge_emoji: "🏆",
        primary_phone: "+961 1 748000",
        primary_email: "contact@deloitte.com.lb",
        website: "https://www2.deloitte.com/lb/en.html",
        linkedin_url: "https://linkedin.com/company/deloitte",
        twitter_url: "https://twitter.com/DeloitteME",
        facebook_url: "https://facebook.com/DeloitteMiddleEast",
        contact_person_name: "Michel Accad",
        contact_person_title: "Country Managing Partner",
        contact_person_email: "maccad@deloitte.com",
        contact_person_phone: "+961 1 748000",
        building_name: "ABC Building",
        area: "Ashrafieh",
        city: "Beirut",
        governorate: "Beirut",
        postal_code: "2034 8303",
        country: "Lebanon",
        year_established: 1926,
        number_of_partners: 45,
        number_of_employees: 850,
        number_of_cpas: 320,
        services_offered: ["Audit", "Tax", "Consulting", "Financial Advisory", "Risk Management"],
        industries: ["Banking", "Real Estate", "Telecommunications", "Healthcare", "Energy"],
        specializations: ["IFRS", "US GAAP", "Forensic Accounting", "Cybersecurity"],
        certifications: ["ISO 9001", "ISO 27001"],
        short_description: "Leading professional services firm providing audit, tax, consulting, and financial advisory services.",
        full_description: "Deloitte is one of the Big Four accounting organizations and the largest professional services network in the world by revenue and number of professionals. In Lebanon, Deloitte has been serving clients for nearly a century.",
        mission_statement: "To make an impact that matters for our clients, our people, and society.",
        vision_statement: "To be the standard of excellence.",
        core_values: ["Integrity", "Outstanding value to markets and clients", "Commitment to each other"],
        commercial_license: "BRT-2024-00001",
        tax_id_number: "TAX-001-2024",
        registration_number: "REG-2024-001",
        membership_status: "Active",
        membership_tier: "Platinum",
        membership_start_date: new Date("2020-01-01"),
        renewal_date: new Date("2025-01-01"),
        is_active: true,
        dues_status: "Paid",
        associated_member_ids: [],
        show_phone: true,
        show_email: true,
        show_website: true,
        show_address: true,
        search_tags: ["audit", "big4", "consulting", "tax", "deloitte"],
        created_at: new Date(),
        updated_at: new Date(),
        annual_contribution: 25000.00,
        sponsorship_level: "Platinum"
    },

    // Big 4 - PwC
    {
        _id: new ObjectId(),
        lacpa_id: "FIRM-2024-002",
        firm_name: "PricewaterhouseCoopers (PwC) Lebanon",
        logo_url: "/assets/images/firms/pwc.svg",
        firm_type: "Audit Firm",
        firm_size: "Big 4",
        badge_color: "orange-600",
        badge_emoji: "🏆",
        primary_phone: "+961 1 985000",
        primary_email: "pwc.lebanon@lb.pwc.com",
        website: "https://www.pwc.com/m1/en/locations/lebanon.html",
        linkedin_url: "https://linkedin.com/company/pwc",
        twitter_url: "https://twitter.com/PwC_Middle_East",
        contact_person_name: "George Najem",
        contact_person_title: "Country Senior Partner",
        contact_person_email: "george.najem@lb.pwc.com",
        building_name: "PwC Building",
        area: "Sin El Fil",
        city: "Beirut",
        postal_code: "1452",
        country: "Lebanon",
        year_established: 1925,
        number_of_partners: 38,
        number_of_employees: 720,
        number_of_cpas: 285,
        services_offered: ["Assurance", "Tax", "Advisory", "Deals", "Consulting"],
        industries: ["Financial Services", "Technology", "Retail", "Manufacturing", "Government"],
        specializations: ["M&A", "Corporate Governance", "Sustainability", "Digital Transformation"],
        certifications: ["ISO 9001", "ISQC 1"],
        short_description: "Global professional services network providing assurance, tax and advisory services.",
        full_description: "PwC is a multinational professional services network with firms in 156 countries. In Lebanon, PwC has been building trust and delivering sustained outcomes for over 95 years.",
        mission_statement: "To build trust in society and solve important problems.",
        vision_statement: "To be the most trusted and influential professional services firm.",
        core_values: ["Act with integrity", "Make a difference", "Care", "Work together"],
        commercial_license: "BRT-2024-00002",
        tax_id_number: "TAX-002-2024",
        registration_number: "REG-2024-002",
        membership_status: "Active",
        membership_tier: "Platinum",
        membership_start_date: new Date("2020-01-01"),
        renewal_date: new Date("2025-01-01"),
        is_active: true,
        dues_status: "Paid",
        show_phone: true,
        show_email: true,
        show_website: true,
        show_address: true,
        search_tags: ["audit", "big4", "pwc", "assurance", "deals"],
        created_at: new Date(),
        updated_at: new Date(),
        annual_contribution: 25000.00
    },

    // Big 4 - EY
    {
        _id: new ObjectId(),
        lacpa_id: "FIRM-2024-003",
        firm_name: "Ernst & Young (EY) Lebanon",
        logo_url: "/assets/images/firms/ey.svg",
        firm_type: "Audit Firm",
        firm_size: "Big 4",
        badge_color: "yellow-600",
        badge_emoji: "🏆",
        primary_phone: "+961 1 985655",
        primary_email: "ey.lebanon@lb.ey.com",
        website: "https://www.ey.com/en_lb",
        linkedin_url: "https://linkedin.com/company/ernstandyoung",
        contact_person_name: "Naji Khoury",
        contact_person_title: "Managing Partner",
        building_name: "EY Building",
        area: "Dbayeh",
        city: "Mount Lebanon",
        postal_code: "90-1299",
        country: "Lebanon",
        year_established: 1924,
        number_of_partners: 42,
        number_of_employees: 780,
        number_of_cpas: 295,
        services_offered: ["Assurance", "Tax", "Strategy and Transactions", "Consulting"],
        industries: ["Consumer Products", "Life Sciences", "Technology", "Financial Services", "Real Estate"],
        specializations: ["IPO Advisory", "Transaction Support", "Business Restructuring", "IT Risk"],
        certifications: ["ISO 9001", "ISO 14001"],
        short_description: "Global leader in assurance, tax, transaction and advisory services.",
        full_description: "EY is a global leader in assurance, consulting, strategy and transactions, and tax services. Building a better working world.",
        mission_statement: "Building a better working world.",
        vision_statement: "To be the world's leading professional services organization.",
        core_values: ["Integrity", "Respect", "Teaming", "Inclusiveness"],
        membership_status: "Active",
        membership_tier: "Platinum",
        membership_start_date: new Date("2020-01-01"),
        renewal_date: new Date("2025-01-01"),
        is_active: true,
        dues_status: "Paid",
        show_phone: true,
        show_email: true,
        show_website: true,
        search_tags: ["audit", "big4", "ey", "transactions", "consulting"],
        created_at: new Date(),
        updated_at: new Date(),
        annual_contribution: 25000.00
    },

    // Big 4 - KPMG
    {
        _id: new ObjectId(),
        lacpa_id: "FIRM-2024-004",
        firm_name: "KPMG Lebanon",
        logo_url: "/assets/images/firms/kpmg.svg",
        firm_type: "Audit Firm",
        firm_size: "Big 4",
        badge_color: "blue-800",
        badge_emoji: "🏆",
        primary_phone: "+961 1 364500",
        primary_email: "info@kpmg.com.lb",
        website: "https://home.kpmg/lb/en/home.html",
        linkedin_url: "https://linkedin.com/company/kpmg",
        contact_person_name: "Fadi Kamel",
        contact_person_title: "Senior Partner",
        building_name: "KPMG Center",
        street: "Clemenceau Street",
        city: "Beirut",
        postal_code: "11-2267",
        country: "Lebanon",
        year_established: 1970,
        number_of_partners: 35,
        number_of_employees: 650,
        number_of_cpas: 270,
        services_offered: ["Audit", "Tax", "Advisory", "Deal Advisory", "Technology"],
        industries: ["Insurance", "Banking", "Energy", "Infrastructure", "Hospitality"],
        specializations: ["Risk Consulting", "Data Analytics", "ESG Advisory", "Regulatory Compliance"],
        certifications: ["ISO 9001", "ISO 27001"],
        short_description: "Professional services firm providing audit, tax and advisory services globally.",
        mission_statement: "To turn knowledge into value for the benefit of our clients, our people and the capital markets.",
        membership_status: "Active",
        membership_tier: "Platinum",
        membership_start_date: new Date("2020-01-01"),
        renewal_date: new Date("2025-01-01"),
        is_active: true,
        dues_status: "Paid",
        show_phone: true,
        show_email: true,
        show_website: true,
        search_tags: ["audit", "big4", "kpmg", "advisory", "risk"],
        created_at: new Date(),
        updated_at: new Date(),
        annual_contribution: 25000.00
    },

    // Large - BDO
    {
        _id: new ObjectId(),
        lacpa_id: "FIRM-2024-005",
        firm_name: "BDO Lebanon",
        logo_url: "/assets/images/firms/bdo.svg",
        firm_type: "Audit Firm",
        firm_size: "Large",
        badge_color: "green-600",
        badge_emoji: "⭐",
        primary_phone: "+961 1 366290",
        primary_email: "info@bdo.com.lb",
        website: "https://www.bdo.lb",
        linkedin_url: "https://linkedin.com/company/bdo",
        contact_person_name: "Antoine Gholam",
        contact_person_title: "Managing Partner",
        building_name: "Mayflower Center",
        area: "Ain El Mreisseh",
        city: "Beirut",
        postal_code: "11-4351",
        country: "Lebanon",
        year_established: 1985,
        number_of_partners: 18,
        number_of_employees: 280,
        number_of_cpas: 95,
        services_offered: ["Audit", "Tax", "Advisory", "Outsourcing", "Valuation"],
        industries: ["Real Estate", "Healthcare", "Education", "Retail", "Manufacturing"],
        specializations: ["Family Business", "Private Equity", "Forensic Services"],
        certifications: ["ISO 9001"],
        short_description: "Leading mid-tier accounting and advisory firm serving diverse clients.",
        mission_statement: "To help people and businesses succeed.",
        membership_status: "Active",
        membership_tier: "Gold",
        membership_start_date: new Date("2021-03-01"),
        renewal_date: new Date("2025-03-01"),
        is_active: true,
        dues_status: "Paid",
        show_phone: true,
        show_email: true,
        show_website: true,
        show_address: true,
        search_tags: ["audit", "large", "bdo", "advisory"],
        created_at: new Date(),
        updated_at: new Date(),
        annual_contribution: 12000.00
    },

    // Large - Grant Thornton
    {
        _id: new ObjectId(),
        lacpa_id: "FIRM-2024-006",
        firm_name: "Grant Thornton Lebanon",
        logo_url: "/assets/images/firms/grant-thornton.svg",
        firm_type: "Audit Firm",
        firm_size: "Large",
        badge_color: "purple-600",
        badge_emoji: "⭐",
        primary_phone: "+961 1 389501",
        primary_email: "contact@gt.com.lb",
        website: "https://www.grantthornton.com.lb",
        linkedin_url: "https://linkedin.com/company/grant-thornton",
        contact_person_name: "Ramzi Hobeika",
        contact_person_title: "Country Managing Partner",
        building_name: "Grant Thornton Building",
        area: "Hazmieh",
        city: "Mount Lebanon",
        postal_code: "1105",
        country: "Lebanon",
        year_established: 1995,
        number_of_partners: 15,
        number_of_employees: 220,
        number_of_cpas: 85,
        services_offered: ["Audit", "Tax", "Business Advisory", "Forensic", "IT Advisory"],
        industries: ["Financial Services", "Construction", "Media", "NGOs", "Automotive"],
        specializations: ["Business Risk Services", "Transaction Advisory", "Growth Services"],
        certifications: ["ISO 9001"],
        short_description: "Leading business advisor to dynamic organizations and private businesses.",
        mission_statement: "To make a difference to our clients, colleagues and communities.",
        membership_status: "Active",
        membership_tier: "Gold",
        membership_start_date: new Date("2021-06-01"),
        renewal_date: new Date("2025-06-01"),
        is_active: true,
        dues_status: "Paid",
        show_phone: true,
        show_email: true,
        show_website: true,
        show_address: true,
        search_tags: ["audit", "large", "grant-thornton", "business-advisory"],
        created_at: new Date(),
        updated_at: new Date(),
        annual_contribution: 12000.00
    },

    // Medium - Semaan, Gholam & Co.
    {
        _id: new ObjectId(),
        lacpa_id: "FIRM-2024-007",
        firm_name: "Semaan, Gholam & Co.",
        logo_url: "/assets/images/firms/semaan-gholam.png",
        firm_type: "Accounting Firm",
        firm_size: "Medium",
        badge_color: "indigo-600",
        badge_emoji: "💼",
        primary_phone: "+961 1 580580",
        primary_email: "info@sgco.com.lb",
        website: "https://www.sgco.com.lb",
        contact_person_name: "Joseph Semaan",
        contact_person_title: "Senior Partner",
        building_name: "Semaan Building",
        area: "Achrafieh",
        city: "Beirut",
        postal_code: "11-0235",
        country: "Lebanon",
        year_established: 2000,
        number_of_partners: 8,
        number_of_employees: 95,
        number_of_cpas: 42,
        services_offered: ["Accounting", "Auditing", "Tax Compliance", "Bookkeeping", "Payroll"],
        industries: ["SMEs", "Trading", "Services", "Import/Export"],
        specializations: ["Lebanese Tax Law", "SME Advisory", "Compliance"],
        short_description: "Trusted accounting firm serving small and medium enterprises.",
        mission_statement: "To provide reliable, accurate and timely accounting services.",
        membership_status: "Active",
        membership_tier: "Silver",
        membership_start_date: new Date("2022-01-01"),
        renewal_date: new Date("2025-01-01"),
        is_active: true,
        dues_status: "Paid",
        show_phone: true,
        show_email: true,
        show_website: true,
        search_tags: ["accounting", "medium", "sme", "tax"],
        created_at: new Date(),
        updated_at: new Date(),
        annual_contribution: 6000.00
    },

    // Medium - Fiduciaire
    {
        _id: new ObjectId(),
        lacpa_id: "FIRM-2024-008",
        firm_name: "Fiduciaire du Liban SAL",
        logo_url: "/assets/images/firms/fiduciaire.png",
        firm_type: "Accounting Firm",
        firm_size: "Medium",
        badge_color: "teal-600",
        badge_emoji: "💼",
        primary_phone: "+961 1 200300",
        primary_email: "contact@fiduciaire.com.lb",
        website: "https://www.fiduciaire-liban.com",
        contact_person_name: "Pierre Khoury",
        contact_person_title: "Managing Partner",
        building_name: "Fiduciaire Center",
        area: "Hamra",
        city: "Beirut",
        postal_code: "11-3421",
        country: "Lebanon",
        year_established: 1998,
        number_of_partners: 6,
        number_of_employees: 75,
        number_of_cpas: 35,
        services_offered: ["Accounting", "Tax Services", "Company Formation", "Legal Compliance"],
        industries: ["Professional Services", "Hospitality", "Retail", "Technology"],
        specializations: ["Corporate Structuring", "Expatriate Tax", "Offshore Services"],
        short_description: "Comprehensive accounting and business services firm.",
        mission_statement: "To deliver exceptional accounting services with integrity.",
        membership_status: "Active",
        membership_tier: "Silver",
        membership_start_date: new Date("2022-04-01"),
        renewal_date: new Date("2025-04-01"),
        is_active: true,
        dues_status: "Paid",
        show_phone: true,
        show_email: true,
        show_website: true,
        show_address: true,
        search_tags: ["accounting", "medium", "corporate", "tax"],
        created_at: new Date(),
        updated_at: new Date(),
        annual_contribution: 6000.00
    },

    // Small - Khalil & Associates
    {
        _id: new ObjectId(),
        lacpa_id: "FIRM-2024-009",
        firm_name: "Khalil & Associates",
        logo_url: "/assets/images/firms/khalil.png",
        firm_type: "Consultancy",
        firm_size: "Small",
        badge_color: "pink-600",
        badge_emoji: "📊",
        primary_phone: "+961 1 445566",
        primary_email: "info@khalilassociates.com",
        contact_person_name: "Samir Khalil",
        contact_person_title: "Founder & Principal Consultant",
        building_name: "Office 301, Tower A",
        area: "Verdun",
        city: "Beirut",
        postal_code: "11-2045",
        country: "Lebanon",
        year_established: 2015,
        number_of_partners: 2,
        number_of_employees: 18,
        number_of_cpas: 8,
        services_offered: ["Financial Consulting", "Business Planning", "Internal Audit", "Training"],
        industries: ["Startups", "SMEs", "NGOs"],
        specializations: ["Startup Advisory", "Financial Modeling", "Fundraising Support"],
        short_description: "Boutique consultancy specializing in financial advisory for growing businesses.",
        mission_statement: "To empower businesses through strategic financial guidance.",
        membership_status: "Active",
        membership_tier: "Bronze",
        membership_start_date: new Date("2023-01-01"),
        renewal_date: new Date("2025-01-01"),
        is_active: true,
        dues_status: "Paid",
        show_phone: true,
        show_email: true,
        search_tags: ["consultancy", "small", "startup", "advisory"],
        created_at: new Date(),
        updated_at: new Date(),
        annual_contribution: 3000.00
    },

    // Small - Najjar CPA
    {
        _id: new ObjectId(),
        lacpa_id: "FIRM-2024-010",
        firm_name: "Najjar CPA Firm",
        logo_url: "/assets/images/firms/najjar.png",
        firm_type: "Accounting Firm",
        firm_size: "Small",
        badge_color: "gray-600",
        badge_emoji: "📊",
        primary_phone: "+961 3 123456",
        primary_email: "m.najjar@najjarcpa.com",
        contact_person_name: "Marwan Najjar",
        contact_person_title: "CPA, Owner",
        building_name: "Office 12, Building C",
        area: "Jounieh",
        city: "Jounieh",
        governorate: "Mount Lebanon",
        postal_code: "2041",
        country: "Lebanon",
        year_established: 2018,
        number_of_partners: 1,
        number_of_employees: 12,
        number_of_cpas: 5,
        services_offered: ["Tax Preparation", "Bookkeeping", "Financial Statements", "Advisory"],
        industries: ["Individuals", "Small Business", "Freelancers"],
        specializations: ["Personal Tax", "Small Business Accounting"],
        short_description: "Local CPA firm serving individuals and small businesses.",
        mission_statement: "To provide accurate, affordable accounting services with a personal touch.",
        membership_status: "Active",
        membership_tier: "Bronze",
        membership_start_date: new Date("2023-06-01"),
        renewal_date: new Date("2025-06-01"),
        is_active: true,
        dues_status: "Paid",
        show_phone: true,
        show_email: true,
        search_tags: ["accounting", "small", "tax", "cpa"],
        created_at: new Date(),
        updated_at: new Date(),
        annual_contribution: 3000.00
    }
];

// Main seeding function
async function seedFirms() {
    const client = new MongoClient(MONGO_URI);

    try {
        // Connect to MongoDB
        console.log('🔌 Connecting to MongoDB...');
        await client.connect();
        console.log('✅ Connected to MongoDB');

        const db = client.db(DB_NAME);
        const firmsCollection = db.collection('firm_members');

        // Optional: Clear existing firms (uncomment if you want to reset)
        // console.log('🗑️  Clearing existing firms...');
        // await firmsCollection.deleteMany({});

        // Insert firms
        console.log('\n📝 Inserting firm members...');
        const result = await firmsCollection.insertMany(firms);

        console.log('\n✅ Successfully inserted', result.insertedCount, 'firm members!');
        console.log('\n📊 Breakdown:');
        console.log('   - Big 4 firms: 4');
        console.log('   - Large firms: 2');
        console.log('   - Medium firms: 2');
        console.log('   - Small firms: 2');
        console.log('\n🎉 Database seeding completed!');
        console.log('\n💡 You can now view firms at: http://localhost:3000/membership/firms');

    } catch (error) {
        console.error('❌ Error seeding database:', error);
        process.exit(1);
    } finally {
        await client.close();
        console.log('\n🔌 Disconnected from MongoDB');
    }
}

// Run the seeding function
seedFirms();
